# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv('cardekho_imputated.csv',index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  str
 1   brand              15411 non-null  str
 2   model              15411 non-null  str
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  str
 6   fuel_type          15411 non-null  str
 7   transmission_type  15411 non-null  str
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), str(6)
memory usage: 2.3 MB

In [4]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

## Data Cleaning
### Handling Missing values

* Handling Missing values 
* Handling Duplicates
* Check data type
* Understand the dataset

In [5]:
## Check Null Values
##Check features with nan value
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [6]:
## Remove Unnecessary Columns
df.drop(columns=['car_name','brand'],inplace=True)
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [7]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [8]:
## Getting All Different Types OF Features
num_features = [feature for feature in df.columns if df[feature].dtype != 'str']
print('Num of Numerical Features :', len(num_features))

cat_features = [feature for feature in df.columns if df[feature].dtype =='str']
print('Num of Categorical Features :', len(cat_features))

discrete_features = [feature for feature in num_features if len(df[feature].unique()) <= 25]
print('Num of Discrete Features :',len(discrete_features))

continuous_features = [feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))

Num of Numerical Features : 7
Num of Categorical Features : 4
Num of Discrete Features : 2
Num of Continuous Features : 5

In [9]:
#Independent and dependent features
X = df.drop(['selling_price'],axis=1)
y = df['selling_price']

## Feature Encoding and Scaling
**One Hot Encoding for Columns which had lesser unique values and not ordinal**
* One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [11]:
df['seller_type'].unique()

<ArrowStringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str

In [12]:
df['fuel_type'].unique()

<ArrowStringArray>
['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
Length: 5, dtype: str

In [13]:
df['transmission_type'].unique()

<ArrowStringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

In [14]:
num_features = X.select_dtypes(exclude='object').columns
onehot_features = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('ohe',OneHotEncoder(drop='first'),onehot_features),
        ('Sc',StandardScaler(),num_features)
    ],remainder='passthrough'
)

In [15]:
num_features

Index(['model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power',
       'seats'],
      dtype='str')

In [16]:
X = preprocessor.fit_transform(X)

In [17]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

In [18]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]], shape=(12328, 14))

## Model Training And Model Selection

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Lasso ,Ridge,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [20]:
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true ,predicted)
    rmse = root_mean_squared_error(true,predicted)
    r2_square = r2_score(true,predicted)
    return mae,mse,rmse,r2_square

In [21]:
models = {
    'Linear Regression' : LinearRegression(),
    'Logistic Regression' : LogisticRegression(),
    'Ridge' : Ridge(),
    'Lasso' : Lasso(),
    'ElasticNet': ElasticNet(),
    'DecisionTreeRegressor' : DecisionTreeRegressor(),
    'RandomForestRegressor' : RandomForestRegressor(),
    'KNeighborsRegressor' : KNeighborsRegressor(),
    'GradientBoostingRegressor' : GradientBoostingRegressor(),
    'AdaBoostRegressor' : AdaBoostRegressor(estimator=DecisionTreeRegressor(random_state=42),random_state=42)
    }

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train,y_train) #train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mae , model_train_mse , model_train_rmse ,model_train_r2 = evaluate_model(y_train,y_train_pred)

    model_test_mae , model_test_mse , model_test_rmse ,model_test_r2 = evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- Mean Squared Error: {:.4f}".format(model_train_mse))
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- Mean Squared Error: {:.4f}".format(model_test_mse))
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Mean Absolute Error: 268101.6071
- Mean Squared Error: 306756099359.7596
- Root Mean Squared Error: 553855.6665
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Mean Absolute Error: 279618.5794
- Mean Squared Error: 252550062888.5654
- Root Mean Squared Error: 502543.5930
- R2 Score: 0.6645
===================================


Logistic Regression
Model performance for Training set
- Mean Absolute Error: 192239.2927
- Mean Squared Error: 202705074302.4010
- Root Mean Squared Error: 450227.8027
- R2 Score: 0.7501
----------------------------------
Model performance for Test set
- Mean Absolute Error: 210308.5063
- Mean Squared Error: 228848147183.1414
- Root Mean Squared Error: 478380.7554
- R2 Score: 0.6960
===================================


Ridge
Model performance for Training set
- Mean Absolute Error: 268059.8015
- Mean Squared Error: 306756818740.9266
- Root Mean Squared Error: 553856.3160
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Mean Absolute Error: 279557.2169
- Mean Squared Error: 252540243247.9685
- Root Mean Squared Error: 502533.8230
- R2 Score: 0.6645
===================================


Lasso
Model performance for Training set
- Mean Absolute Error: 268099.2226
- Mean Squared Error: 306756104248.3742
- Root Mean Squared Error: 553855.6710
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Mean Absolute Error: 279614.7461
- Mean Squared Error: 252549134806.7814
- Root Mean Squared Error: 502542.6696
- R2 Score: 0.6645
===================================


ElasticNet
Model performance for Training set
- Mean Absolute Error: 234917.5425
- Mean Squared Error: 350183784377.0143
- Root Mean Squared Error: 591763.2841
- R2 Score: 0.5682
----------------------------------
Model performance for Test set
- Mean Absolute Error: 247149.5035
- Mean Squared Error: 288742980900.8583
- Root Mean Squared Error: 537348.1003
- R2 Score: 0.6164
===================================


DecisionTreeRegressor
Model performance for Training set
- Mean Absolute Error: 5164.8199
- Mean Squared Error: 432524990.5364
- Root Mean Squared Error: 20797.2352
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Mean Absolute Error: 124021.1563
- Mean Squared Error: 93250848504.9960
- Root Mean Squared Error: 305370.0190
- R2 Score: 0.8761
===================================


RandomForestRegressor
Model performance for Training set
- Mean Absolute Error: 39960.5132
- Mean Squared Error: 20302175014.7052
- Root Mean Squared Error: 142485.7011
- R2 Score: 0.9750
----------------------------------
Model performance for Test set
- Mean Absolute Error: 101914.3381
- Mean Squared Error: 52876925955.0448
- Root Mean Squared Error: 229949.8336
- R2 Score: 0.9298
===================================


KNeighborsRegressor
Model performance for Training set
- Mean Absolute Error: 91395.5548
- Mean Squared Error: 106199175807.9169
- Root Mean Squared Error: 325882.1502
- R2 Score: 0.8691
----------------------------------
Model performance for Test set
- Mean Absolute Error: 112578.2436
- Mean Squared Error: 64079155016.4207
- Root Mean Squared Error: 253138.6083
- R2 Score: 0.9149
===================================


GradientBoostingRegressor
Model performance for Training set
- Mean Absolute Error: 111709.5558
- Mean Squared Error: 42002252335.7090
- Root Mean Squared Error: 204944.5104
- R2 Score: 0.9482
----------------------------------
Model performance for Test set
- Mean Absolute Error: 126393.9629
- Mean Squared Error: 65288787574.6468
- Root Mean Squared Error: 255516.7070
- R2 Score: 0.9133
===================================


AdaBoostRegressor
Model performance for Training set
- Mean Absolute Error: 15335.3490
- Mean Squared Error: 1012984234.4854
- Root Mean Squared Error: 31827.4133
- R2 Score: 0.9988
----------------------------------
Model performance for Test set
- Mean Absolute Error: 99357.1302
- Mean Squared Error: 46756395213.0495
- Root Mean Squared Error: 216232.2714
- R2 Score: 0.9379
===================================

In [22]:
rf_params = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [None, 5, 10, 15, 20],
    "max_features": ["sqrt", "log2"],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "criterion": ['absolute_error', 'poisson', 'friedman_mse', 'squared_error'],
    "bootstrap": [True, False]
}
knn_params = {
    "n_neighbors": [3, 5, 7, 9, 11, 15],
    "weights": ["uniform", "distance"],
    "algorithm": ["auto", "ball_tree", "kd_tree", "brute"],
    "leaf_size": [20, 30, 40, 50],
    "p": [1, 2]
}

ada_params = {
    "n_estimators": [50, 100, 200, 300, 500, 800],
    "learning_rate": [0.001, 0.01, 0.05, 0.1, 0.5, 1.0],
    "loss": ["linear", "square", "exponential"],
    "estimator__max_depth": [1, 2, 3, 4, 5, 6, 8],
    "estimator__min_samples_split": [2, 5, 10],
    "estimator__min_samples_leaf": [1, 2, 4]
}

gb_params = {
    "n_estimators": [100, 200, 300, 500, 1000],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [2, 3, 5, 7, 10],
    "subsample": [0.8, 1.0],
    "max_features": [None, "sqrt", "log2", 5, 7, 8],
    "criterion": ["friedman_mse", "squared_error"],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 2, 4]
}

In [23]:
randomcv_models = [('Knn',KNeighborsRegressor(),knn_params),
                    ('rf',RandomForestRegressor(),rf_params),
                    ('ada',AdaBoostRegressor(estimator=DecisionTreeRegressor(random_state=42),random_state=42),ada_params),
                    ('Gb_reg',GradientBoostingRegressor(),gb_params)
                    ]

In [24]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}

for name, model, params in randomcv_models:
    random = RandomizedSearchCV(
    estimator=model,
    param_distributions=params,
    n_iter=100,
    cv=5,
    scoring="neg_root_mean_squared_error",
    verbose=3,
    n_jobs=-1,
    random_state=42
    )

    random.fit(X_train, y_train)

    model_param[name] = {
        "best_params": random.best_params_,
        "best_model": random.best_estimator_
    }

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name]["best_params"])

Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV 3/5] END algorithm=kd_tree, leaf_size=50, n_neighbors=5, p=1, weights=uniform;, score=-239251.187 total time=   0.0s
[CV 1/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=7, p=2, weights=uniform;, score=-299042.433 total time=   0.1s
[CV 2/5] END algorithm=kd_tree, leaf_size=50, n_neighbors=5, p=1, weights=uniform;, score=-603688.682 total time=   0.1s
[CV 5/5] END algorithm=kd_tree, leaf_size=50, n_neighbors=5, p=1, weights=uniform;, score=-336280.642 total time=   0.1s
[CV 1/5] END algorithm=kd_tree, leaf_size=50, n_neighbors=5, p=1, weights=uniform;, score=-303507.918 total time=   0.1s
[CV 2/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=7, p=2, weights=uniform;, score=-671619.513 total time=   0.1s
[CV 3/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=7, p=2, weights=uniform;, score=-246351.070 total time=   0.1s
[CV 4/5] END algorithm=kd_tree, leaf_size=50, n_neighbors=5, p=1, weights=uniform;, score=-253891.780 total time=   0.1s
[CV 5/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=7, p=2, weights=uniform;, score=-360580.080 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=7, p=2, weights=uniform;, score=-266726.631 total time=   0.0s
[CV 2/5] END algorithm=brute, leaf_size=40, n_neighbors=11, p=2, weights=distance;, score=-692937.286 total time=   0.1s
[CV 1/5] END algorithm=brute, leaf_size=40, n_neighbors=11, p=2, weights=distance;, score=-277200.166 total time=   0.1s
[CV 4/5] END algorithm=brute, leaf_size=40, n_neighbors=11, p=2, weights=distance;, score=-251463.525 total time=   0.1s
[CV 5/5] END algorithm=brute, leaf_size=40, n_neighbors=11, p=2, weights=distance;, score=-391045.755 total time=   0.1s
[CV 3/5] END algorithm=brute, leaf_size=40, n_neighbors=11, p=2, weights=distance;, score=-258027.756 total time=   0.1s
[CV 1/5] END algorithm=auto, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-298648.014 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-642044.457 total time=   0.1s
[CV 5/5] END algorithm=auto, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-358772.414 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-246442.163 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-250996.858 total time=   0.1s
[CV 1/5] END algorithm=brute, leaf_size=30, n_neighbors=15, p=1, weights=uniform;, score=-315151.507 total time=   0.2s
[CV 3/5] END algorithm=brute, leaf_size=30, n_neighbors=15, p=1, weights=uniform;, score=-301595.630 total time=   0.2s
[CV 5/5] END algorithm=brute, leaf_size=30, n_neighbors=15, p=1, weights=uniform;, score=-417461.199 total time=   0.2s
[CV 2/5] END algorithm=brute, leaf_size=30, n_neighbors=15, p=1, weights=uniform;, score=-719641.508 total time=   0.2s
[CV 4/5] END algorithm=brute, leaf_size=30, n_neighbors=15, p=1, weights=uniform;, score=-280888.631 total time=   0.2s
[CV 1/5] END algorithm=auto, leaf_size=30, n_neighbors=7, p=1, weights=distance;, score=-271593.448 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=30, n_neighbors=7, p=1, weights=distance;, score=-629345.202 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=30, n_neighbors=7, p=1, weights=distance;, score=-225762.928 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=30, n_neighbors=7, p=1, weights=distance;, score=-233598.130 total time=   0.1s
[CV 4/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=1, weights=uniform;, score=-259018.494 total time=   0.2s
[CV 5/5] END algorithm=auto, leaf_size=30, n_neighbors=7, p=1, weights=distance;, score=-326340.159 total time=   0.1s
[CV 3/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=1, weights=uniform;, score=-263579.527 total time=   0.2s
[CV 2/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=1, weights=uniform;, score=-671129.903 total time=   0.2s
[CV 5/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=1, weights=uniform;, score=-365319.942 total time=   0.2s
[CV 1/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=1, weights=uniform;, score=-299849.114 total time=   0.2s
[CV 1/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=2, weights=distance;, score=-273769.336 total time=   0.1s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=11, p=2, weights=uniform;, score=-306319.078 total time=   0.2s
[CV 2/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=2, weights=distance;, score=-672703.492 total time=   0.1s
[CV 3/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=2, weights=distance;, score=-246807.232 total time=   0.1s
[CV 4/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=2, weights=distance;, score=-250197.814 total time=   0.1s
[CV 5/5] END algorithm=brute, leaf_size=50, n_neighbors=9, p=2, weights=distance;, score=-370851.132 total time=   0.1s
[CV 4/5] END algorithm=kd_tree, leaf_size=30, n_neighbors=15, p=2, weights=uniform;, score=-284964.578 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=11, p=2, weights=uniform;, score=-703107.295 total time=   0.2s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=11, p=2, weights=uniform;, score=-411562.811 total time=   0.2s
[CV 2/5] END algorithm=kd_tree, leaf_size=30, n_neighbors=15, p=2, weights=uniform;, score=-734609.703 total time=   0.1s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=11, p=2, weights=uniform;, score=-276084.842 total time=   0.2s
[CV 1/5] END algorithm=kd_tree, leaf_size=30, n_neighbors=15, p=2, weights=uniform;, score=-319501.860 total time=   0.1s
[CV 3/5] END algorithm=kd_tree, leaf_size=30, n_neighbors=15, p=2, weights=uniform;, score=-296544.097 total time=   0.1s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=11, p=2, weights=uniform;, score=-286138.407 total time=   0.2s
[CV 2/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=1, weights=distance;, score=-599628.554 total time=   0.0s
[CV 5/5] END algorithm=kd_tree, leaf_size=30, n_neighbors=15, p=2, weights=uniform;, score=-427575.435 total time=   0.1s
[CV 1/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=1, weights=distance;, score=-272548.049 total time=   0.1s
[CV 5/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=1, weights=distance;, score=-310059.168 total time=   0.1s
[CV 3/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=1, weights=distance;, score=-219453.725 total time=   0.1s
[CV 1/5] END algorithm=kd_tree, leaf_size=20, n_neighbors=3, p=2, weights=distance;, score=-262591.498 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=1, weights=distance;, score=-239133.538 total time=   0.1s
[CV 2/5] END algorithm=kd_tree, leaf_size=20, n_neighbors=3, p=2, weights=distance;, score=-654538.477 total time=   0.0s
[CV 3/5] END algorithm=kd_tree, leaf_size=20, n_neighbors=3, p=2, weights=distance;, score=-246505.923 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, leaf_size=20, n_neighbors=3, p=2, weights=distance;, score=-276793.243 total time=   0.0s
[CV 5/5] END algorithm=kd_tree, leaf_size=20, n_neighbors=3, p=2, weights=distance;, score=-422269.792 total time=   0.0s
[CV 1/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=15, p=1, weights=distance;, score=-276834.630 total time=   0.1s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=15, p=2, weights=uniform;, score=-296549.635 total time=   0.2s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=15, p=2, weights=uniform;, score=-734572.944 total time=   0.2s
[CV 3/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=15, p=1, weights=distance;, score=-260190.612 total time=   0.1s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=15, p=2, weights=uniform;, score=-284929.615 total time=   0.2s
[CV 2/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=15, p=1, weights=distance;, score=-696648.046 total time=   0.1s
[CV 4/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=15, p=1, weights=distance;, score=-244499.167 total time=   0.1s
[CV 5/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=15, p=1, weights=distance;, score=-379526.185 total time=   0.1s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=2, weights=uniform;, score=-269156.809 total time=   0.1s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=15, p=2, weights=uniform;, score=-319466.042 total time=   0.3s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=2, weights=uniform;, score=-387305.437 total time=   0.1s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=2, weights=uniform;, score=-678413.943 total time=   0.2s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=15, p=2, weights=uniform;, score=-427572.342 total time=   0.3s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=2, weights=uniform;, score=-299312.302 total time=   0.2s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=2, weights=uniform;, score=-272390.113 total time=   0.2s
[CV 1/5] END algorithm=ball_tree, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-269543.139 total time=   0.2s
[CV 2/5] END algorithm=ball_tree, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-692281.000 total time=   0.2s
[CV 3/5] END algorithm=ball_tree, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-233877.376 total time=   0.2s
[CV 4/5] END algorithm=ball_tree, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-265375.165 total time=   0.2s
[CV 1/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-298643.215 total time=   0.2s
[CV 3/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-246505.185 total time=   0.2s
[CV 1/5] END algorithm=brute, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-269582.154 total time=   0.1s
[CV 3/5] END algorithm=brute, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-234107.432 total time=   0.1s
[CV 2/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-692273.474 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-331801.965 total time=   0.2s
[CV 2/5] END algorithm=brute, leaf_size=50, n_neighbors=3, p=1, weights=uniform;, score=-543050.456 total time=   0.2s
[CV 5/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-358757.203 total time=   0.2s
[CV 5/5] END algorithm=brute, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-331772.779 total time=   0.1s
[CV 3/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-233866.821 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-265350.479 total time=   0.0s
[CV 2/5] END algorithm=brute, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-692305.776 total time=   0.1s
[CV 4/5] END algorithm=brute, leaf_size=50, n_neighbors=5, p=2, weights=distance;, score=-265367.652 total time=   0.1s
[CV 5/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-331822.310 total time=   0.0s
[CV 4/5] END algorithm=brute, leaf_size=50, n_neighbors=3, p=1, weights=uniform;, score=-273700.807 total time=   0.2s
[CV 1/5] END algorithm=auto, leaf_size=30, n_neighbors=11, p=2, weights=uniform;, score=-306327.323 total time=   0.1s
[CV 1/5] END algorithm=kd_tree, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-269571.633 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=30, n_neighbors=11, p=2, weights=uniform;, score=-286146.983 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-251004.254 total time=   0.2s
[CV 2/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=7, p=1, weights=uniform;, score=-641992.247 total time=   0.2s
[CV 2/5] END algorithm=auto, leaf_size=30, n_neighbors=9, p=2, weights=distance;, score=-672710.570 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=30, n_neighbors=11, p=2, weights=uniform;, score=-703132.357 total time=   0.1s
[CV 5/5] END algorithm=auto, leaf_size=30, n_neighbors=11, p=2, weights=uniform;, score=-411568.189 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=30, n_neighbors=9, p=2, weights=distance;, score=-250359.279 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=30, n_neighbors=11, p=2, weights=uniform;, score=-276087.635 total time=   0.1s
[CV 1/5] END algorithm=brute, leaf_size=50, n_neighbors=3, p=1, weights=uniform;, score=-296122.069 total time=   0.2s
[CV 3/5] END algorithm=auto, leaf_size=30, n_neighbors=9, p=2, weights=distance;, score=-246772.651 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=7, p=1, weights=distance;, score=-271593.448 total time=   0.1s
[CV 1/5] END algorithm=auto, leaf_size=30, n_neighbors=9, p=2, weights=distance;, score=-273725.523 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=7, p=1, weights=distance;, score=-225762.928 total time=   0.1s
[CV 5/5] END algorithm=auto, leaf_size=30, n_neighbors=9, p=2, weights=distance;, score=-370845.284 total time=   0.1s
[CV 3/5] END algorithm=brute, leaf_size=50, n_neighbors=3, p=1, weights=uniform;, score=-231148.329 total time=   0.2s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=7, p=1, weights=distance;, score=-326340.159 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=7, p=1, weights=distance;, score=-629345.202 total time=   0.1s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=9, p=2, weights=distance;, score=-273725.523 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=9, p=2, weights=distance;, score=-246772.651 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=50, n_neighbors=15, p=1, weights=distance;, score=-696648.046 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=7, p=1, weights=distance;, score=-233598.130 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-692273.474 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=50, n_neighbors=15, p=1, weights=distance;, score=-244499.167 total time=   0.1s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=9, p=2, weights=distance;, score=-370845.284 total time=   0.1s
[CV 5/5] END algorithm=brute, leaf_size=50, n_neighbors=3, p=1, weights=uniform;, score=-234520.665 total time=   0.2s
[CV 1/5] END algorithm=auto, leaf_size=50, n_neighbors=15, p=1, weights=distance;, score=-276834.630 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-265350.479 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=9, p=2, weights=distance;, score=-250359.279 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-233866.821 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=9, p=2, weights=distance;, score=-672710.570 total time=   0.1s
[CV 5/5] END algorithm=auto, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-331822.310 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=40, n_neighbors=5, p=2, weights=distance;, score=-269571.633 total time=   0.1s
[CV 3/5] END algorithm=auto, leaf_size=50, n_neighbors=15, p=1, weights=distance;, score=-260190.612 total time=   0.1s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, p=1, weights=uniform;, score=-296199.179 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, p=1, weights=uniform;, score=-231033.772 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=50, n_neighbors=15, p=1, weights=distance;, score=-379526.185 total time=   0.1s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, p=1, weights=uniform;, score=-234524.300 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, p=1, weights=uniform;, score=-542970.575 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, p=1, weights=uniform;, score=-273739.807 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=3, p=1, weights=distance;, score=-277450.382 total time=   0.1s
[CV 5/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=3, p=1, weights=distance;, score=-246865.109 total time=   0.2s
[CV 3/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=3, p=1, weights=distance;, score=-235474.767 total time=   0.2s
[CV 2/5] END algorithm=brute, leaf_size=40, n_neighbors=15, p=1, weights=uniform;, score=-719641.508 total time=   0.2s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-299787.050 total time=   0.1s
[CV 2/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=3, p=1, weights=distance;, score=-543249.135 total time=   0.1s
[CV 4/5] END algorithm=brute, leaf_size=40, n_neighbors=15, p=1, weights=uniform;, score=-280888.631 total time=   0.2s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-263587.650 total time=   0.1s
[CV 2/5] END algorithm=brute, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-671129.903 total time=   0.2s
[CV 4/5] END algorithm=brute, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-259018.494 total time=   0.2s
[CV 1/5] END algorithm=brute, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-299849.114 total time=   0.3s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-671134.220 total time=   0.1s
[CV 4/5] END algorithm=ball_tree, leaf_size=40, n_neighbors=3, p=1, weights=distance;, score=-254851.788 total time=   0.2s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-365360.463 total time=   0.1s
[CV 2/5] END algorithm=auto, leaf_size=30, n_neighbors=3, p=1, weights=distance;, score=-543234.364 total time=   0.0s
[CV 1/5] END algorithm=brute, leaf_size=40, n_neighbors=15, p=1, weights=uniform;, score=-315151.507 total time=   0.2s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-259011.126 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=30, n_neighbors=3, p=1, weights=distance;, score=-254755.978 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=30, n_neighbors=3, p=1, weights=distance;, score=-277511.582 total time=   0.0s
[CV 3/5] END algorithm=brute, leaf_size=40, n_neighbors=15, p=1, weights=uniform;, score=-301595.630 total time=   0.2s
[CV 3/5] END algorithm=auto, leaf_size=30, n_neighbors=3, p=1, weights=distance;, score=-235413.510 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=30, n_neighbors=3, p=1, weights=distance;, score=-246846.812 total time=   0.0s
[CV 5/5] END algorithm=brute, leaf_size=40, n_neighbors=15, p=1, weights=uniform;, score=-417461.199 total time=   0.2s
[CV 2/5] END algorithm=auto, leaf_size=50, n_neighbors=5, p=2, weights=uniform;, score=-697816.710 total time=   0.1s
[CV 4/5] END algorithm=auto, leaf_size=50, n_neighbors=5, p=2, weights=uniform;, score=-285443.429 total time=   0.0s
[CV 5/5] END algorithm=brute, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-365319.942 total time=   0.2s
[CV 3/5] END algorithm=brute, leaf_size=20, n_neighbors=9, p=1, weights=uniform;, score=-263579.527 total time=   0.2s
[CV 3/5] END algorithm=auto, leaf_size=50, n_neighbors=5, p=2, weights=uniform;, score=-252894.959 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=50, n_neighbors=5, p=2, weights=uniform;, score=-337044.840 total time=   0.1s
[CV 1/5] END algorithm=ball_tree, leaf_size=30, n_neighbors=11, p=1, weights=distance;, score=-273684.948 total time=   0.1s

In [25]:
for model_name in model_param:

    # Use the best fitted model directly from RandomizedSearchCV
    model = model_param[model_name]["best_model"]

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(model_name)

    print('Model performance for Training set')
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- Mean Squared Error: {:.4f}".format(model_train_mse))
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- Mean Squared Error: {:.4f}".format(model_test_mse))
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('=' * 35)
    print("\n")

Knn
Model performance for Training set
- Mean Absolute Error: 5208.6578
- Mean Squared Error: 437180145.4683
- Root Mean Squared Error: 20908.8533
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Mean Absolute Error: 105990.4690
- Mean Squared Error: 68595025815.2379
- Root Mean Squared Error: 261906.5211
- R2 Score: 0.9089
===================================


rf
Model performance for Training set
- Mean Absolute Error: 45014.3288
- Mean Squared Error: 4186674607.6231
- Root Mean Squared Error: 64704.5177
- R2 Score: 0.9948
----------------------------------
Model performance for Test set
- Mean Absolute Error: 96421.9237
- Mean Squared Error: 41504229978.7962
- Root Mean Squared Error: 203725.8697
- R2 Score: 0.9449
===================================


ada
Model performance for Training set
- Mean Absolute Error: 94834.0323
- Mean Squared Error: 19357626751.7912
- Root Mean Squared Error: 139131.6885
- R2 Score: 0.9761
----------------------------------
Model performance for Test set
- Mean Absolute Error: 119698.2569
- Mean Squared Error: 65598861293.4372
- Root Mean Squared Error: 256122.7465
- R2 Score: 0.9129
===================================


Gb_reg
Model performance for Training set
- Mean Absolute Error: 74899.9283
- Mean Squared Error: 12414669732.7997
- Root Mean Squared Error: 111421.1368
- R2 Score: 0.9847
----------------------------------
Model performance for Test set
- Mean Absolute Error: 97589.9351
- Mean Squared Error: 41609910905.8752
- Root Mean Squared Error: 203985.0752
- R2 Score: 0.9447
===================================